# Generated by Django 5.2.10 on 2026-01-27 10:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_start_hours_ago', models.IntegerField()),
                ('period_end_hours_ago', models.IntegerField()),
                ('total_trades', models.IntegerField(default=0)),
                ('total_buys', models.IntegerField(default=0)),
                ('total_sells', models.IntegerField(default=0)),
                ('total_volume_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unique_markets', models.IntegerField(default=0)),
                ('buy_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sell_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('redeem_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('split_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('merge_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('reward_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cash_flow_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('subgraph_realized_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('subgraph_total_bought', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('subgraph_total_positions', models.IntegerField(blank=True, null=True)),
                ('win_rate_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('profit_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_drawdown_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_id', models.CharField(db_index=True, max_length=66, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('icon', models.URLField(blank=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('winning_outcome', models.CharField(blank=True, max_length=100)),
                ('resolution_timestamp', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=42, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('pseudonym', models.CharField(blank=True, max_length=100)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('subgraph_realized_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('subgraph_total_bought', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('subgraph_total_positions', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='CopyTradingScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slippage_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('slippage_mode', models.CharField(choices=[('percentage', 'Percentage'), ('points', 'Points')], max_length=20)),
                ('total_trades_copied', models.IntegerField(default=0)),
                ('total_volume_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('original_pnl_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('estimated_copy_pnl_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pnl_difference_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pnl_difference_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profitable', models.BooleanField(default=False)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_scenarios', to='wallet_analysis.analysisrun')),
            ],
            options={
                'ordering': ['slippage_value'],
            },
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='wallet_analysis.wallet'),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(db_index=True, max_length=66)),
                ('asset', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.IntegerField(db_index=True)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('outcome', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('size', models.DecimalField(decimal_places=6, max_digits=20)),
                ('total_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='wallet_analysis.market')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='wallet_analysis.wallet')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['wallet', 'timestamp'], name='wallet_anal_wallet__389823_idx'), models.Index(fields=['wallet', 'side'], name='wallet_anal_wallet__c39cc9_idx')],
                'constraints': [models.UniqueConstraint(fields=('transaction_hash', 'asset', 'size', 'price', 'side'), name='unique_trade')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('avg_price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('realized_pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_bought', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='wallet_analysis.wallet')),
            ],
            options={
                'ordering': ['-realized_pnl'],
                'constraints': [models.UniqueConstraint(fields=('wallet', 'token_id'), name='unique_wallet_position')],
            },
        ),
        migrations.CreateModel(
            name='CurrentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=100)),
                ('outcome', models.CharField(max_length=100)),
                ('size', models.DecimalField(decimal_places=6, max_digits=20)),
                ('avg_price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cash_pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percent_pnl', models.DecimalField(decimal_places=4, max_digits=10)),
                ('realized_pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cur_price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('redeemable', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_positions', to='wallet_analysis.market')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_positions', to='wallet_analysis.wallet')),
            ],
            options={
                'ordering': ['-initial_value'],
                'constraints': [models.UniqueConstraint(fields=('wallet', 'asset'), name='unique_wallet_current_position')],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('REDEEM', 'Redeem'), ('SPLIT', 'Split'), ('MERGE', 'Merge'), ('REWARD', 'Reward'), ('CONVERSION', 'Conversion')], db_index=True, max_length=20)),
                ('transaction_hash', models.CharField(db_index=True, max_length=66)),
                ('timestamp', models.IntegerField(db_index=True)),
                ('datetime', models.DateTimeField()),
                ('size', models.DecimalField(decimal_places=6, max_digits=20)),
                ('usdc_size', models.DecimalField(decimal_places=6, max_digits=20)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='wallet_analysis.market')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='wallet_analysis.wallet')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['wallet', 'activity_type'], name='wallet_anal_wallet__a2c5b4_idx'), models.Index(fields=['wallet', 'timestamp'], name='wallet_anal_wallet__799b69_idx')],
            },
        ),
    ]
