# Generated by Django 5.2.10 on 2026-01-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='data_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='data_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
