# Generated by Django 5.2.10 on 2026-01-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_analysis', '0002_add_wallet_date_range'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('transaction_hash', 'activity_type', 'size', 'usdc_size'), name='unique_activity'),
        ),
    ]
