# Generated by Django 5.0.2 on 2026-02-16 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_analysis', '0009_analysisrun_avg_cost_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='avg_cost_cache_max_activity_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='avg_cost_cache_max_trade_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['wallet', 'activity_type', 'market'], name='wallet_anal_wallet__8431bb_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['wallet', '-timestamp'], name='wallet_anal_wallet__8d17b9_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['wallet', 'market'], name='wallet_anal_wallet__8a2a49_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['wallet', 'side', 'market'], name='wallet_anal_wallet__b2d7ac_idx'),
        ),
    ]
