# Generated by Django 5.0.2 on 2026-02-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_analysis', '0010_analysisrun_avg_cost_cache_max_activity_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='neg_risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='market',
            name='neg_risk_market_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Condition-id of the parent neg-risk market (from CLOB API).', max_length=66),
        ),
    ]
